name: CI/CD pipeline

on:
  pull_request:
    branches:
      - master
      - develop
  push:
    branches:
      - master

jobs:
  prepare:
    env:
      CI: true

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use defined node version
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Dependencies cache
        uses: actions/cache@v1
        env:
          cache-name: node-modules-cache
        with:
          path: ~/.cache/yarn
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install dependencies
        run: yarn install --frozen-lockfile

  verify:
    if: github.event_name == 'pull_request'
    needs: prepare
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Linter
        run: yarn lint

      - name: Unit tests
        run: yarn test

  deploy_production:
    if: (github.event_name == 'push' && github.ref == 'refs/heads/master')
    needs: prepare
    runs-on: ubuntu-latest

    env:
      NODE_ENV: production

    steps:
      - uses: actions/checkout@v2
      - name: Build project
        run: yarn build

      - name: List files
        run: tree -L 2 && ls -lap

      - name: Deploy
        run: echo "Deploying to $NODE_ENV..."
