name: Integrate

on:
  pull_request:
    branches:
      - master
      - develop

jobs:
  build:
    env:
      CI: true

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use defined Node version
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Linter
        run: yarn lint

      - name: Unit tests
        run: yarn test
